name: Deploy React App to Azure Web App via Docker

on:
  push:
    branches: main-1

jobs:
  build_and_deploy:
    name: Build, Push Docker Image to Docker Hub, and Deploy to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}  # Use the GitHub commit SHA as the image tag
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/msal:${IMAGE_TAG} .
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/msal:${{ env.IMAGE_TAG }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Docker Image to Azure Web App
        run: |
          az webapp config container set --name 'msal-webapp-docker' \
            --resource-group 'msal' \
            --container-image-name ${{ secrets.DOCKERHUB_USERNAME }}/msal:${{ env.IMAGE_TAG }} \
            --container-registry-url https://index.docker.io/v1/ \
            --container-registry-user ${{ secrets.DOCKERHUB_USERNAME }} \
            --container-registry-password ${{ secrets.DOCKERHUB_PASSWORD }}
